# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leezw
email: lee@leezw.net
description: 一本书有20%讲的是知识，80%帮助你理解知识。有时我们可以跳过那80%。
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://leezw.net" # the base hostname & protocol for your site
github_username:  mzzw
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
