# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leezw
email: lee@leezw.net
description: 一本书有少部分讲的是知识，大部分帮助你理解知识。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leezw.net" # the base hostname & protocol for your site
github_username: mzzw
paginate: 10
permalink: /posts/:title
theme-dark: false #Set to true to change to dark website theme
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator:  '<!-- more -->'
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      categories: "posts"
      comments: true
  - scope:
      path: "assets/pictures"
    values:
      picture: true
  - scope:
      path: "assets/pdf"
    values:
      pdf: true

plugins: [jekyll-paginate,jekyll-admin, kramdown,jekyll-seo-tag,jemoji,jekyll-redirect-from]
# Build settings
markdown: kramdown
highlighter: rouge
